version: "3.8"

services:
  kafka1:
    image: confluentinc/cp-kafka:7.2.1
    ports:
      - "9091:9092"
    environment:
      CLUSTER_ID: ZGI1NTk0YmY3NzVjNDk5MD
      KAFKA_NODE_ID: 1
      KAFKA_LISTENERS: CLIENT://0.0.0.0:9092,CONTROLLER://kafka1:29093,INTERNAL://kafka1:29092
      KAFKA_ADVERTISED_LISTENERS: CLIENT://localhost:9091,INTERNAL://kafka1:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CLIENT:PLAINTEXT,CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka1:29093"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ./run_workaround.sh:/tmp/run_workaround.sh
    command: "bash -c '/tmp/run_workaround.sh && /etc/confluent/docker/run'"
  kafka2:
    image: confluentinc/cp-kafka:7.2.1
    depends_on:
      - kafka1
    ports:
      - "9092:9092"
    environment:
      CLUSTER_ID: ZGI1NTk0YmY3NzVjNDk5MD
      KAFKA_NODE_ID: 2
      KAFKA_LISTENERS: CLIENT://0.0.0.0:9092,CONTROLLER://kafka2:29093,INTERNAL://kafka2:29092
      KAFKA_ADVERTISED_LISTENERS: CLIENT://localhost:9092,INTERNAL://kafka2:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CLIENT:PLAINTEXT,CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: "2@kafka2:29093,1@kafka1:29093"
    volumes:
      - ./run_workaround.sh:/tmp/run_workaround.sh
    command: "bash -c '/tmp/run_workaround.sh && /etc/confluent/docker/run'"
  kafka3:
    image: confluentinc/cp-kafka:7.2.1
    depends_on:
      - kafka1
      - kafka2
    ports:
      - "9093:9092"
    environment:
      CLUSTER_ID: ZGI1NTk0YmY3NzVjNDk5MD
      KAFKA_NODE_ID: 3
      KAFKA_LISTENERS: CLIENT://0.0.0.0:9092,CONTROLLER://kafka3:29093,INTERNAL://kafka3:29092
      KAFKA_ADVERTISED_LISTENERS: CLIENT://localhost:9093,INTERNAL://kafka3:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CLIENT:PLAINTEXT,CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: "3@kafka3:29093,1@kafka1:29093"

    volumes:
      - ./run_workaround.sh:/tmp/run_workaround.sh
    command: "bash -c '/tmp/run_workaround.sh && /etc/confluent/docker/run'"
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    depends_on:
      - kafka1
      - kafka2
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1:29092,kafka2:29092
      DYNAMIC_CONFIG_ENABLED: 'true'